"""create new table quizzes

Revision ID: 612516e6b363
Revises: 76ac6d49aeb5
Create Date: 2026-01-31 02:03:38.313164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '612516e6b363'
down_revision: Union[str, Sequence[str], None] = '76ac6d49aeb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(50), nullable=False),
    sa.Column('email', sa.String(50), nullable=False),
    sa.Column('hashed_password', sa.String(255), nullable=False),
    sa.Column('role', sa.String(50), nullable=False),
    sa.Column('id', sa.String(36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_table('students',
    sa.Column('first_name', sa.String(50), nullable=False),
    sa.Column('last_name', sa.String(50), nullable=False),
    sa.Column('grade_lvl', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(36), nullable=True),
    sa.Column('id', sa.String(36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quizzes',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('quiz_num', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('unit', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('students')
    op.drop_table('quizzes')
    # ### end Alembic commands ###
