"""dropped quizzes and quizes table

Revision ID: 76ac6d49aeb5
Revises: 1a36ed8e05cc
Create Date: 2026-01-31 02:01:46.098042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76ac6d49aeb5'
down_revision: Union[str, Sequence[str], None] = '1a36ed8e05cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
