"""add new colum total_items in quizzes table

Revision ID: c14fe101b5d6
Revises: 612516e6b363
Create Date: 2026-01-31 13:00:46.599517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c14fe101b5d6'
down_revision: Union[str, Sequence[str], None] = '612516e6b363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('total_items', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'total_items')
    # ### end Alembic commands ###
