"""rename column request_role to role

Revision ID: ef6a887d23f4
Revises: 64cadd9d804c
Create Date: 2026-03-18 13:17:10.610851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef6a887d23f4'
down_revision: Union[str, Sequence[str], None] = '64cadd9d804c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration_requests', sa.Column('role', sa.String(), nullable=False))
    op.drop_column('registration_requests', 'request_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration_requests', sa.Column('request_role', sa.VARCHAR(), nullable=False))
    op.drop_column('registration_requests', 'role')
    # ### end Alembic commands ###
