"""add new table user

Revision ID: f2660f3eac3e
Revises: a46253bc87c0
Create Date: 2026-02-02 13:55:16.547464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2660f3eac3e'
down_revision: Union[str, Sequence[str], None] = 'a46253bc87c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('hased_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # Use batch mode for existing table alterations
    with op.batch_alter_table("students") as batch_op:
        # Add the user_id column as nullable (so it won't break existing rows)
        batch_op.add_column(sa.Column('user_id', sa.String(), nullable=True))
        # Create FK safely
        batch_op.create_foreign_key("fk_students_user_id_users", 'users', ['user_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table("students") as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("user_id")

    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
