"""add new table user

Revision ID: f2660f3eac3e
Revises: a46253bc87c0
Create Date: 2026-02-02 13:55:16.547464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2660f3eac3e'
down_revision: Union[str, Sequence[str], None] = 'a46253bc87c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass


def downgrade() -> None:
    """Downgrade schema."""
    pass
